### ISSUE TITLE
Media Theme deployment fails for custom domain with HTTP Forbidden, allow deployment to default domain (NEST-527)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/DotNest-Support#56]
Related to https://lombiq.atlassian.net/browse/NEST-506. You can get the following error when you try to deploy to a site with a custom domain:

```
Deployment failed with the following exception: System.Net.Http.HttpRequestException: Remote deployment to *** failed with the HTTP code Forbidden and message "Method: POST, RequestUri: '***', Version: 1.1, Content: System.Net.Http.MultipartFormDataContent, Headers:
{
  Content-Type: multipart/form-data; boundary="a7609e87-9e56-4c4a-8157-22ccd7c672a0"
  Content-Length: 6396
}".
   at Lombiq.Hosting.MediaTheme.Deployer.RemoteDeploymentHelper.DeployAsync(CommandLineOptions options, String deploymentPackagePath) in /home/runner/work/Hosting-Media-Theme/Hosting-Media-Theme/Lombiq.Hosting.MediaTheme.Deployer/RemoteDeploymentHelper.cs:line 50
   at Lombiq.Hosting.MediaTheme.Deployer.Program.RunOptionsInnerAsync(CommandLineOptions options) in /home/runner/work/Hosting-Media-Theme/Hosting-Media-Theme/Lombiq.Hosting.MediaTheme.Deployer/Program.cs:line 2[48](https://github.com/Lombiq/DotNest-Core-Sites-SDK/actions/runs/7994854894/job/21833876190#step:3:51)
   at Lombiq.Hosting.MediaTheme.Deployer.Program.RunOptionsAsync(CommandLineOptions options) in /home/runner/work/Hosting-Media-Theme/Hosting-Media-Theme/Lombiq.Hosting.MediaTheme.Deployer/Program.cs:line 98
```

This is because Cloudflare, by default, will block requests to _ /OrchardCore.Deployment.Remote/ImportRemoteInstance/Import_, thinking it's a bot.

We either need to force everyone using custom domains to disable bot fight mode (or pay for Cloudflare's Pro plan to enable such configuration), or we can allow such deployments to go to the default domains instead. For that, we need to prevent the custom domain redirects to this URL.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-527)

**Comment by Piedone** [comment]
We fixed this since then by allowing deployments to the default URL, [see knowledge base](https://dotnest.com/knowledge-base/topics/custom-domains#:~:text=If%20you%20do%20Media%20Theme%20theming%20for%20your%20site%2C%20then%20be%20sure%20to%20keep%20remote%20deployments%20pointing%20still%20to%20your%20site%27s%20standard%20dotnest.net%20domain.%20You%20may%20get%20%22Remote%20deployment%20to%20...%20failed%20with%20the%20HTTP%20code%20Forbidden...%22%20errors%20due%20to%20Cloudflare%27s%20Bot%20Fight%20Mode%20otherwise.).
